language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx
sudo: false

# Run builds for all the supported trains
rust:
  - nightly
  - stable

before_script:
  - export PATH=$PATH:~/.cargo/bin

# The main build
script:
  - cargo build
  - cargo test
  # Run Clippy at the end because compiling takes long and Clippy is broken on
  # Rust nightly often.
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo install clippy --force && cargo clippy
      fi
